plugin_selector.plugin_configuration.plugin_selector.plugin_selector_base:
  type: mapping
  mapping:
    collect_plugin_configuration:
      label: Collect plugin configuration
      type: boolean
    keep_previously_selected_plugins:
      label: Keep previously selected plugins
      type: boolean
    label:
      label: Label
      type: label
    name:
      label: Required
      type: boolean

plugin_selector.plugin_configuration.plugin_selector.plugin_selector_radios:
  type: plugin_selector.plugin_configuration.plugin_selector.plugin_selector_base

plugin_selector.plugin_configuration.plugin_selector.plugin_selector_select_list:
  type: plugin_selector.plugin_configuration.plugin_selector.plugin_selector_base
